---
- hosts: docker_boxes
  tasks:
  - name: Install packages
    apt:
      name: git, apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common
      state: present
      update_cache: yes
    become: yes

  - name: Add Docker’s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes      

  - name: Set up the stable repository for Docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
    become: yes      

  - name: Install Docker
    apt:
      name: docker-ce,docker-ce-cli,containerd.io
      state: present
      update_cache: yes  
    become: yes        

  - name: Add linux_user to docker group
    user: 
      name: "{{linux_user}}"
      groups: docker
      append: yes
    become: yes
    
  - name: Download the current stable release of Docker Compose
    uri:
      url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      creates: /usr/local/bin/docker-compose
    become: yes
  
  - name: Apply executable permissions to the binary
    shell: sudo chmod +x /usr/local/bin/docker-compose
    become: yes

  # - name: Login to docker group
  #   shell: newgrp docker    
    
  - name: Reset ssh connection to allow user changes to affect 'current login user'
    meta: reset_connection  

- hosts: elk_boxes
  tasks:
  - name: Download ELK project from GIT
    git:
      repo: "https://github.com/deviantony/docker-elk.git"
      dest: "/home/{{linux_user}}/docker-elk"

  - name: Start ELK Containers
    shell: "cd /home/{{linux_user}}/docker-elk && docker-compose up -d"

- hosts: zabbix_boxes
  tasks:
  - name: Download zabbix project from GIT
    git:
      repo: "https://github.com/zabbix/zabbix-docker.git"
      dest: "/home/{{linux_user}}/zabbix-docker" 
      
  - name: Start Zabbix Containers
    shell: "cd /home/{{linux_user}}/zabbix-docker && docker-compose -f ./docker-compose_v3_alpine_mysql_latest.yaml up -d"      

- hosts: windows_servers
  tasks:
  - name: Install IIS Web-Server with sub features and management tools
    win_feature:
      name: Web-Server
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: win_feature

  - name: Reboot if installing Web-Server feature requires it
    win_reboot:
    when: win_feature.reboot_required
 
  - name: Check if Filebeat service is installed
    win_service:
      name: Filebeat
    register: filebeat_service_info

  - name: Create Download folder
    win_file:
      path: C:\Downloads
      state: directory

  - name: Download Filebeat
    win_get_url:
      url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.7.1-windows-x86_64.zip"
      dest: C:\Downloads
    when: filebeat_service_info.exists == false

  - name: Unzip Filebeat
    win_unzip:
        dest: "C:\\Program Files"
        src: "C:\\Downloads\\filebeat-oss-7.7.1-windows-x86_64.zip"
        delete_archive: yes 
    when: filebeat_service_info.exists == false        

  - name: Rename Filebeat folder
    win_shell: Rename-Item "C:\\Program Files\\filebeat-7.7.1-windows-x86_64" Filebeat
    args:
        creates: "C:\\Program Files\\Filebeat"
    when: filebeat_service_info.exists == false        

  - name: Install Filebeat Service
    win_shell: .\install-service-filebeat.ps1
    args:
      chdir: C:\Program Files\Filebeat
    when: filebeat_service_info.exists == false   

  - name: Enable IIS module in Filebeat
    win_command: filebeat.exe modules enable iis
    args:
      chdir: C:\Program Files\Filebeat
      creates: C:\Program Files\Filebeat\modules.d\iis.yml

  - name: Copy Filebeat.yml
    win_copy:
        src: config/filebeat.yml
        dest: C:\Program Files\Filebeat\filebeat.yml
        force: yes
    register: filebeat_config_changed

  - name: Restart Filebeat Service
    win_service:
      name: filebeat
      start_mode: auto
      state: restarted   
    when: filebeat_config_changed.changed == true

  - name: Check if Zabbix service is installed
    win_service:
      name: "Zabbix Agent"
    register: zabbix_service_info  

  - name: Download Zabbix
    win_get_url:
      url: "https://www.zabbix.com/downloads/5.0.1/zabbix_agent-5.0.1-windows-amd64.zip"
      dest: C:\Downloads
    when: zabbix_service_info.exists == false

  - name: Unzip Zabbix
    win_unzip:
        dest: "C:\\Program Files\\Zabbix"
        src: "C:\\Downloads\\zabbix_agent-5.0.1-windows-amd64.zip"
        delete_archive: yes
    when: zabbix_service_info.exists == false

  - name: Copy zabbix_agentd.conf
    win_copy:
        src: config/zabbix_agentd.conf
        dest: C:\Program Files\Zabbix\conf\zabbix_agentd.conf
        force: yes
    register: zabbix_config_changed 
    
  - name: Register Zabbix service
    win_command: zabbix_agentd.exe --config "C:\Program Files\Zabbix\conf\zabbix_agentd.conf" --install
    args:
      chdir: C:\Program Files\Zabbix\bin
    when: zabbix_service_info.exists == false
    
  - name: Restart Zabbix Service
    win_service:
      name: "zabbix agent"
      start_mode: auto
      state: restarted   
    when: zabbix_config_changed.changed == true  
