---
# tasks file for install_winlogbeat
- name: Create Download folder
  win_file:
    path: C:\Downloads
    state: directory
    
- name: Check if Winlogbeat service is installed
  win_service:
    name: Winlogbeat
  register: winlogbeat_service_info

- name: Download Winlogbeat
  win_get_url:
    url: "https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-7.7.1-windows-x86_64.zip"
    dest: C:\Downloads
  when: winlogbeat_service_info.exists == false     

- name: Unzip Winlogbeat
  win_unzip:
      dest: "C:\\Program Files"
      src: "C:\\Downloads\\winlogbeat-7.7.1-windows-x86_64.zip"
      delete_archive: yes 
  when: winlogbeat_service_info.exists == false     


- name: Rename Winlogbeat folder
  win_shell: Rename-Item "C:\\Program Files\\winlogbeat-7.7.1-windows-x86_64" Winlogbeat
  args:
      creates: "C:\\Program Files\\Winlogbeat"
  when: winlogbeat_service_info.exists == false     

- name: Install Winlogbeat Service
  win_shell: .\install-service-winlogbeat.ps1
  args:
    chdir: C:\Program Files\Winlogbeat
  when: winlogbeat_service_info.exists == false     

- name: Copy Winlogbeat.yml
  win_copy:
      src: files/winlogbeat.yml
      dest: C:\Program Files\Winlogbeat\Winlogbeat.yml
      force: yes
  register: winlogbeat_config_changed   

- name: Restart Winlogbeat Service
  win_service:
    name: winlogbeat
    start_mode: auto
    state: restarted   
  when: winlogbeat_config_changed.changed == true         
